
#------------------------------------------------------
# Homepage Controller
#------------------------------------------------------

api_homepage:
    path:     /
    defaults: { _controller: ApiBundle:Default:index }

#------------------------------------------------------
# Ping Controller
#------------------------------------------------------

api_ping:
    path:     /ping
    defaults: { _controller: ApiBundle:Ping:index }

api_ping_post:
    path:     /ping/post
    defaults: { _controller: ApiBundle:Ping:post }
    methods:  [POST]

api_ping_inner:
    path:     /ping/inner
    defaults: { _controller: ApiBundle:Ping:inner }

#------------------------------------------------------
# User Controller
#------------------------------------------------------

api_user:
    path:     /user
    defaults: { _controller: ApiBundle:User:index }

api_user_add:
    path:     /user/add
    defaults: { _controller: ApiBundle:User:add }
    methods:  [POST]

api_user_login:
    path:     /user/login
    defaults: { _controller: ApiBundle:User:login }
    methods:  [POST]

api_user_is_valide_token:
    path:     /user/isValideToken
    defaults: { _controller: ApiBundle:User:isValideToken }
    methods:  [POST]

#------------------------------------------------------
# Community Controller
#------------------------------------------------------

api_community:
    path:     /community
    defaults: { _controller: ApiBundle:Community:index }
    methods:  [GET, POST]

api_community_add:
    path:     /community/add
    defaults: { _controller: ApiBundle:Community:add }
    methods:  [POST]

api_community_delete:
    path:     /community/delete/{id}
    defaults: { _controller: ApiBundle:Community:delete }
    methods:  [DELETE, POST, GET]

api_community_my_communities:
    path:     /community/myCommunities
    defaults: { _controller: ApiBundle:Community:myCommunities }
    methods:  [GET, POST]

api_community_user_communities:
    path:     /community/userCommunities/{id}
    defaults: { _controller: ApiBundle:Community:userCommunities }
    methods:  [GET, POST]


#------------------------------------------------------
# Idea Controller
#------------------------------------------------------

api_idea:
    path:     /idea
    defaults: { _controller: ApiBundle:Idea:index }
    methods:  [POST, GET]

api_idea_add:
    path:     /idea/add
    defaults: { _controller: ApiBundle:Idea:add }
    methods:  [POST]