<?php

namespace ApiBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VoteUserCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoteUserCommentRepository extends EntityRepository
{
}
